project:
  type: website
  output-dir: _site

website:
  title: ""
  navbar:
    logo: images/kelvinalytics-logo.png
    logo-alt: "Kelvinalytics"
    left:
      - text: Hands-On Exercise
        menu:
          - text: Overview
            href: hands-on.qmd
          - text: Exercise 1
            href: hands-on/exercise1.qmd
          - text: Exercise 2
            href: hands-on/exercise2.qmd
          - text: Exercise 3
            href: hands-on/exercise3.qmd
          - text: Exercise 4
            href: hands-on/exercise4.qmd
          - text: Exercise 5
            href: hands-on/exercise5.qmd

      - text: In-Class Exercise
        menu:
          - text: Overview
            href: in-class.qmd
          - text: Exercise 1
            href: "https://public.tableau.com/app/profile/kelvin.andikko/viz/In-ClassExercise1_17772813239940/Dashboard1?publish=yes"
          - text: Exercise 2A
            href: "https://public.tableau.com/app/profile/kelvin.andikko/viz/In-ClassExercise3_17777053254330/SuperstoreSalesandProfitReport?publish=yes"
          - text: Exercise 2B
            href: "https://public.tableau.com/app/profile/kelvin.andikko/viz/In-ClassExercise3b_17777067088260/PopulationPyramidofSingaporebyPlanningArea2025?publish=yes"
          - text: Exercise 3A
            href: "https://public.tableau.com/app/profile/kelvin.andikko/viz/In-ClassExericse4a/ExamDataofPrimary3Students?publish=yes"
          - text: Exercise 3B
            href: "https://public.tableau.com/app/profile/kelvin.andikko/viz/In-ClassExericse4b/FoodServiceKPIReport?publish=yes"
            
      - text: Take-Home Exercise 1
        menu: 
          - text: Technical Report
            href: take-home-1/technical-report.qmd
          - text: Executive Summary
            href: take-home-1/exec-summary.qmd
      
      - text: Assignments
        menu:
          - text: Overview
            href: assignments.qmd

      - href: about.qmd
        text: About

    right:
      - icon: linkedin
        href: "https://www.linkedin.com/in/kelvinandikko/"

  page-footer:
    left: "Built with Quarto"
    right: "Copyright © 2026 by Kelvin Andikko"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    page-layout: full

editor: visual